import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Map.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Map() {


  return (
    <>
      <Head>
        <title>Geolocation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className} ${styles.main}`}>
        <div>
        </div>
      </main>
    </>
  )
}
